"""users table

Revision ID: 11ac2f6754f6
Revises: a54299cfaaec
Create Date: 2020-04-27 17:35:11.093880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ac2f6754f6'
down_revision = 'a54299cfaaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_user_telephone'), 'user', ['telephone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telephone'), table_name='user')
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
