"""users table

Revision ID: a54299cfaaec
Revises: 089df5688071
Create Date: 2020-04-27 00:46:51.353171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54299cfaaec'
down_revision = '089df5688071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_column('user', 'name')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
